name: vehicle_app
description: Vehicle Manager Application
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rummel_blue_theme:
    path: ../../../../../../resources/rummel_blue_theme
  shared_services:
    path: ../../../../../../resources/shared_services
  vehicle_ui:
    path: ../../packages/vehicle_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
